fixed oops bug
git-svn-id: https://svn.code.sf.net/p/log4sh/svn/trunk@196 f8386e53-771b-0410-ac50-fca19b3aa4be

diff --git a/source/1.3/src/test/test-prop-config b/source/1.3/src/test/test-prop-config
--- a/source/1.3/src/test/test-prop-config
+++ b/source/1.3/src/test/test-prop-config
@@ -25,7 +25,7 @@ loadLog4sh()
   if [ -r log4sh ]; then
     LOG4SH_CONFIGURATION="${config}" . ./log4sh
   else
-    echo "ERROR: could not load (log4sh) >&2"
+    echo "ERROR: could not load (log4sh)" >&2
     exit 1
   fi
   logger_trace "whoAmI=${whoAmI} whereAmI=${whereAmI}"
