added disablement of set workaround for pdksh
git-svn-id: https://svn.code.sf.net/p/log4sh/svn/trunk@382 f8386e53-771b-0410-ac50-fca19b3aa4be

diff --git a/source/1.3/src/shell/log4sh b/source/1.3/src/shell/log4sh
--- a/source/1.3/src/shell/log4sh
+++ b/source/1.3/src/shell/log4sh
@@ -94,16 +94,6 @@ __LOG4SH_IFS_DEFAULT=' '
 
 __LOG4SH_SECONDS=`eval "expr \`date '+%H \* 3600 + %M \* 60 + %S'\`"`
 
-# find workarounds for various commands
-(
-  # determine if the set builtin needs to be evaluated. if the string is parsed
-  # into two separate strings (common in ksh), then set needs to be evaled.
-  str='x{1,2}'
-  set -- ${str}
-  test ! "$1" = 'x1' -a ! "${2:-}" = 'x2'
-)
-__LOG4SH_WA_SET_NEEDS_EVAL=$?
-
 # configure log4sh debugging. set the LOG4SH_INFO environment variable to any
 # non-empty value to enable info output, LOG4SH_DEBUG enable debug output, or
 # LOG4SH_TRACE to enable trace output. log4sh ERROR and above messages are
@@ -131,7 +121,6 @@ unset _log4sh_const
 __log4sh_filename=`basename $0`
 __log4sh_tmpDir=''
 __log4sh_trapsFile=''
-__log4sh_strictBehavior=${__LOG4SH_FALSE}
 
 __log4sh_threadName=${__LOG4SH_THREAD_DEFAULT}
 __log4sh_threadStack=${__LOG4SH_THREAD_DEFAULT}
@@ -139,6 +128,18 @@ __log4sh_threadStack=${__LOG4SH_THREAD_DEFAULT}
 __log4sh_seconds=0
 __log4sh_secondsLast=0
 __log4sh_secondsWrap=0
+
+# workarounds for various commands
+__log4sh_wa_strictBehavior=${__LOG4SH_FALSE}
+(
+  # determine if the set builtin needs to be evaluated. if the string is parsed
+  # into two separate strings (common in ksh), then set needs to be evaled.
+  str='x{1,2}'
+  set -- ${str}
+  test ! "$1" = 'x1' -a ! "${2:-}" = 'x2'
+)
+__log4sh_wa_setNeedsEval=$?
+
 
 #=============================================================================
 # Log4sh
@@ -461,7 +462,7 @@ _log4sh_updateSeconds()
 #*/
 log4sh_enableStrictBehavior()
 {
-  __log4sh_strictBehavior=${__LOG4SH_TRUE}
+  __log4sh_wa_strictBehavior=${__LOG4SH_TRUE}
 }
 
 #/**
@@ -582,23 +583,31 @@ _log4sh_findArrayElement()
 _log4sh_getArrayElement()
 {
   [ -n "${FUNCNAME:-}" ] && ${__LOG4SH_TRACE} "${FUNCNAME}()${BASH_LINENO:+'(called from ${BASH_LINENO})'}"
-  _lgae__array=$1
-  _lgae__index=$2
-  ${__LOG4SH_TRACE} "_lgae__array='${_lgae__array}' _lgae__index='${_lgae__index}'"
+  _lgae_array=$1
+  _lgae_index=$2
+  ${__LOG4SH_TRACE} "_lgae_array='${_lgae_array}' _lgae_index='${_lgae_index}'"
 
-  _lgae__oldIFS=${IFS} IFS=${__LOG4SH_IFS_ARRAY}
-  if [ ${__LOG4SH_WA_SET_NEEDS_EVAL} -eq 0 ]; then
-    set -- junk ${_lgae__array}
+  _lgae_oldIFS=${IFS} IFS=${__LOG4SH_IFS_ARRAY}
+  if [ ${__log4sh_wa_setNeedsEval} -eq 0 ]; then
+    set -- junk ${_lgae_array}
   else
-    eval "set -- junk \"${_lgae__array}\""
-  fi
-  IFS=${_lgae__oldIFS}
-  ${__LOG4SH_TRACE} "1='${1:-}' 2='${2:-}' 3='${3:-}' ..."
+    eval "set -- junk \"${_lgae_array}\""
+    _lgae_arraySize=$#
 
-  shift ${_lgae__index}
+    if [ ${_lgae_arraySize} -le ${__log4shAppenderCount} ]; then
+      # the evaled set *didn't* work; failing back to original set command and
+      # disabling the work around. (pdksh)
+      __log4sh_wa_setNeedsEval=${FALSE}
+      set -- junk ${_lgae_array}
+    fi
+  fi
+  IFS=${_lgae_oldIFS}
+
+  shift ${_lgae_index}
+  ${__LOG4SH_TRACE} "1='${1:-}' 2='${2:-}' 3='${3:-}' ..."
   echo "$1"
 
-  unset _lgae__array _lgae__index _lgae__oldIFS
+  unset _lgae_array _lgae_arraySize _lgae_index _lgae_oldIFS
   return ${__LOG4SH_TRUE}
 }
 
@@ -921,7 +930,7 @@ appender_setLayout()
 #*/
 _appender_getLayoutByIndex()
 {
-  _log4sh_getArrayElement "$__log4shAppenderLayouts" $1
+  _log4sh_getArrayElement "${__log4shAppenderLayouts}" $1
 }
 
 #/**
@@ -1377,8 +1386,10 @@ EOF
 #       <paramdef>string <parameter>appender</parameter></paramdef>
 #     </funcprototype>
 #   </funcsynopsis>
-#   <para>Dynamically regenerates an appender function in memory that is fully
-#   instantiated for a specific logging task.</para>
+#   <para>
+#     Dynamically regenerates an appender function in memory that is fully
+#     instantiated for a specific logging task.
+#     </para>
 #   <funcsynopsis>
 #     <funcsynopsisinfo>_appender_activate myAppender</funcsynopsisinfo>
 #   </funcsynopsis>
@@ -1582,7 +1593,7 @@ EOF
 
   # footer
   cat <<EOF
-  unset _la_layout
+  unset _la_level _la_message _la_layout
 }
 EOF
 
@@ -1934,7 +1945,7 @@ appender_file_setMaxFileSize()
   afsmfs_unit=`expr ${afsmfs_size} : '[0-9]* *\([A-Za-z]\{2,3\}\)'`
 
   # determine multiplier
-  if [ ${__log4sh_strictBehavior} -eq ${__LOG4SH_TRUE} ]; then
+  if [ ${__log4sh_wa_strictBehavior} -eq ${__LOG4SH_TRUE} ]; then
     case "${afsmfs_unit}" in
       KB) afsmfs_unit='KiB' ;;
       MB) afsmfs_unit='MiB' ;;
