found another of log4sh's message that should have been sent to STDERR
git-svn-id: https://svn.code.sf.net/p/log4sh/svn/trunk@154 f8386e53-771b-0410-ac50-fca19b3aa4be

diff --git a/source/1.3/src/shell/log4sh b/source/1.3/src/shell/log4sh
--- a/source/1.3/src/shell/log4sh
+++ b/source/1.3/src/shell/log4sh
@@ -145,7 +145,7 @@ _log4sh_cleanup()
         sed 's/^[0-9]*: //'`
     else
       # unrecognized trap output
-      echo "log4sh:FATAL unable to restore old traps!  unrecognized trap command output"
+      echo "log4sh:FATAL unable to restore old traps!  unrecognized trap command output" >&2
     fi
   fi
    
