- added log4sh_cleanup() function - changed some " chars into ' chars
git-svn-id: https://svn.code.sf.net/p/log4sh/svn/trunk@177 f8386e53-771b-0410-ac50-fca19b3aa4be

diff --git a/source/1.3/src/shell/log4sh b/source/1.3/src/shell/log4sh
--- a/source/1.3/src/shell/log4sh
+++ b/source/1.3/src/shell/log4sh
@@ -3,7 +3,7 @@
 # <?xml version="1.0" encoding="UTF-8"?>
 # <s:shelldoc xmlns:s="http://www.forestent.com/2005/XSL/ShellDoc">
 # <s:header>
-# log4sh 1.3.4pre
+# log4sh 1.3.4
 #
 # http://log4sh.sourceforge.net/
 # 
@@ -27,7 +27,7 @@
 # non-empty value to enable debugging.
 LOG4SH_DEBUG=${LOG4SH_DEBUG:+' '}
 LOG4SH_DEBUG=${LOG4SH_DEBUG:-':'}
-${LOG4SH_DEBUG} echo "log4sh:DEBUG debug output enabled" >&2
+${LOG4SH_DEBUG} echo 'log4sh:DEBUG debug output enabled' >&2
 
 # treat unset variables as an error when substituting
 set -u
@@ -35,7 +35,7 @@ set -u
 #
 # constants
 #
-__LOG4SH_VERSION=1.3.3
+__LOG4SH_VERSION=1.3.4pre
 
 __LOG4SH_TRUE=0
 __LOG4SH_FALSE=1
@@ -69,10 +69,11 @@ __LOG4SH_LEVEL_CLOSED=255
 __LOG4SH_PATTERN_DEFAULT='%d %p - %m%n'
 __LOG4SH_THREAD_DEFAULT='main'
 
-__LOG4SH_DEFAULT_IFS=" "
+__LOG4SH_DEFAULT_IFS=' '
 # the following IFS is *supposed* to be on two lines!!
 __LOG4SH_ARRAY_IFS="
 "
+__LOG4SH_TRAP_EXIT='log4sh-EXIT'
 
 # set the constants to readonly
 for _const in `set |grep "^__LOG4SH_" |cut -d= -f1`; do
@@ -83,7 +84,7 @@ unset _const
 #
 # variables
 #
-__log4sh_filename="`basename $0`"
+__log4sh_filename=`basename $0`
 __log4sh_tmpDir=''
 __log4sh_trapsFile=''
 
@@ -120,6 +121,32 @@ __log4shThreadStack=$__LOG4SH_THREAD_DEFAULT
 # <entry>
 #   <funcsynopsis>
 #     <funcprototype>
+#       <funcdef><function>log4sh_cleanup</function></funcdef>
+#     </funcprototype>
+#   </funcsynopsis>
+#   <para>This is a cleanup function to remove the temporary directory used by
+#   log4sh.  It is provided for scripts who want to do log4sh cleanup work
+#   themselves rather than using the automated cleanup of log4sh that is
+#   invoked upon a normal exit of the script.</para>
+#   <funcsynopsis>
+#     <funcsynopsisinfo>log4sh_cleanup</funcsynopsisinfo>
+#   </funcsynopsis>
+# </entry>
+# </s:function>
+#*/
+log4sh_cleanup()
+{
+  _log4sh_cleanup $__LOG4SH_TRAP_EXIT
+}
+
+#/**
+# <s:function group="miscellaneous">
+# <entry align="right">
+#   <emphasis>void</emphasis>
+# </entry>
+# <entry>
+#   <funcsynopsis>
+#     <funcprototype>
 #       <funcdef><function>_log4sh_cleanup</function></funcdef>
 #       <paramdef>string <parameter>signal</parameter></paramdef>
 #     </funcprototype>
@@ -147,7 +174,7 @@ _log4sh_cleanup()
 
   # these are the only signals that log4sh traps.  no need to list them all
   case "${_trap}" in
-    EXIT) _signal=0 ;;
+    EXIT|${__LOG4SH_TRAP_EXIT}) _signal=0 ;;
     TERM) _signal=15 ;;
   esac
 
@@ -157,20 +184,20 @@ _log4sh_cleanup()
     if [ `grep "^trap -- " "${__log4sh_trapsFile}" >/dev/null; echo $?` -eq 0 ]
     then
       # newer trap command
-      $LOG4SH_DEBUG echo "log4sh:DEBUG newer POSIX trap command"
+      $LOG4SH_DEBUG echo 'log4sh:DEBUG newer POSIX trap command'
       _restoreTrap=${__LOG4SH_TRUE}
       _oldTrap=`grep "${_trap}$" "${__log4sh_trapsFile}" |\
         sed "s/^trap -- \(.*\) [A-Z]*$/\1/"`
     elif [ `grep "[0-9]*: " "${__log4sh_trapsFile}" >/dev/null; echo $?` -eq 0 ]
     then
       # older trap command
-      $LOG4SH_DEBUG echo "log4sh:DEBUG older style trap command"
+      $LOG4SH_DEBUG echo 'log4sh:DEBUG older style trap command'
       _restoreTrap=${__LOG4SH_TRUE}
       _oldTrap=`grep "^${_signal}: " "${__log4sh_trapsFile}" |\
         sed 's/^[0-9]*: //'`
     else
       # unrecognized trap output
-      echo "log4sh:FATAL unable to restore old traps!  unrecognized trap command output" >&2
+      echo 'log4sh:FATAL unable to restore old traps!  unrecognized trap command output' >&2
     fi
   fi
    
@@ -183,14 +210,22 @@ _log4sh_cleanup()
   fi
 
   # exit cleanly
-  if [ "${_trap}" = "EXIT" ]; then
-    _return=${_signal}
-  else
-    _return=`expr 128 + ${_signal}`
-    # disable the EXIT trap
-    trap EXIT
-  fi
-  exit ${_return}
+  case ${_trap} in
+    EXIT|${__LOG4SH_TRAP_EXIT})
+      _return=${_signal}
+      ;;
+    *)
+      _return=`expr 128 + ${_signal}`
+      # disable the EXIT trap
+      trap EXIT
+      ;;
+  esac
+
+  # exit if the trap was not the special log4sh-EXIT trap
+  [ "${_trap}" = ${__LOG4SH_TRAP_EXIT} ] || exit ${_return}
+
+  unset _oldTrap _signal _restoreTrap _trap
+  return ${_return}
 }
 
 #/**
@@ -231,7 +266,7 @@ _log4sh_mktempDir()
 
   _tmpDir="${TMPDIR-/tmp}/log4sh.${_random}"
   ( umask 077 && mkdir "${_tmpDir}" ) || {
-    echo "log4sh:FATAL could not create temporary directory!  exiting" >&2
+    echo 'log4sh:FATAL could not create temporary directory!  exiting' >&2
     exit 1
   }
   echo ${_tmpDir}
@@ -1194,6 +1229,10 @@ _appender_parsePattern()
   fi
   unset _oldIFS
 
+  # escape any '&' chars in the message
+  _msg=`echo "${_msg}" |sed 's/&/\\\\&/g'`
+
+  # parse the pattern
   _pattern=`echo "${_pattern}" |sed \
     -e 's/%c/shell/g' \
     -e 's/%d{[^}]*}/%d/g' -e "s/%d/${_date}/g" \
